Iniciando testes
aHub-Tech/hub-discord pull request #13
Opened 2021-07-26 12:43 UTC by DevRadhy

## O que foi feito
Adicionando testes automatizados com `Jest`

2021-07-26 12:56 UTC, caio-emidio commented on src/tests/entities/Message.spec.ts
> +
Nao eh melhor substituir por um objeto? 
message = {
 guild_id: "860667880479653888",
 message_id: "868343902527189012",
created_at: new Date(1627192898833)
}

2021-07-26 12:58 UTC, DevRadhy commented on src/tests/entities/Message.spec.ts
> +
ok

2021-07-26 14:15 UTC, DevRadhy commented on src/tests/entities/Message.spec.ts
> +
O teste é o da `Entitie` `Message` e `message` não pode receber outra assinatura porque é uma `const`, mas pode ser feita a modificação na classe `Message` para receber os parâmetros no construtor.

2021-07-28 19:35 UTC, vcwild requested changes

2021-08-03 12:29 UTC, closed without merging